<?php

return [
    'ctrl' => [
        'title' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country',
        'label' => 'title',
        'default_sortby' => 'title',
        'tstamp' => 'tstamp',
        'crdate' => 'crdate',
        'cruser_id' => 'cruser_id',
        'delete' => 'deleted',
        'rootLevel' => 1,
        'adminOnly' => true,
        'enablecolumns' => [
            'disabled' => 'hidden'
        ],
        'searchFields' => 'title, iso_code',
        'typeicon_classes' => [
            'default' => 'flags-multiple',
            'mask' => 'flags-###TYPE###'
        ],
        'typeicon_column' => 'flag'
    ],
    'palettes' => [
        'visibility' => [
            'showitem' => 'hidden, enabled',
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.palette.visibility'
        ]
    ],
    'types' => [
        '1' => [
            'showitem' => '--palette--;;visibility, title, iso_code, parameter, flag'
        ]
    ],
    'columns' => [
        'hidden' => [
            'exclude' => true,
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.hidden',
            'config' => [
                'type' => 'check',
                'items' => [
                    [0 => '', 'invertStateDisplay' => true]
                ],
                'default' => 0
            ]
        ],
        'enabled' => [
            'exclude' => true,
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.enabled',
            'config' => [
                'type' => 'check',
                'items' => [
                    [0 => '']
                ],
                'default' => 1
            ]
        ],
        'title' => [
            'exclude' => false,
            'l10n_mode' => 'exclude',
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.title',
            'config' => [
                'type' => 'input',
                'eval' => 'trim,required',
                'default' => ''
            ]
        ],
        'iso_code' => [
            'exclude' => false,
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.iso_code',
            'description' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.iso_code.description',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'eval' => 'trim,required,unique',
                'max' => 2,
                'items' => [
                    ['----', ''], ['AD', 'AD'], ['AE', 'AE'], ['AF', 'AF'], ['AG', 'AG'], ['AI', 'AI'], ['AL', 'AL'], ['AM', 'AM'], ['AO', 'AO'], ['AQ', 'AQ'],
                    ['AR', 'AR'], ['AS', 'AS'], ['AT', 'AT'], ['AU', 'AU'], ['AW', 'AW'], ['AX', 'AX'], ['AZ', 'AZ'], ['BA', 'BA'], ['BB', 'BB'], ['BD', 'BD'],
                    ['BE', 'BE'], ['BF', 'BF'], ['BG', 'BG'], ['BH', 'BH'], ['BI', 'BI'], ['BJ', 'BJ'], ['BL', 'BL'], ['BM', 'BM'], ['BN', 'BN'], ['BO', 'BO'],
                    ['BQ', 'BQ'], ['BR', 'BR'], ['BS', 'BS'], ['BT', 'BT'], ['BV', 'BV'], ['BW', 'BW'], ['BY', 'BY'], ['BZ', 'BZ'], ['CA', 'CA'], ['CC', 'CC'],
                    ['CD', 'CD'], ['CF', 'CF'], ['CG', 'CG'], ['CH', 'CH'], ['CI', 'CI'], ['CK', 'CK'], ['CL', 'CL'], ['CM', 'CM'], ['CN', 'CN'], ['CO', 'CO'],
                    ['CR', 'CR'], ['CU', 'CU'], ['CV', 'CV'], ['CW', 'CW'], ['CX', 'CX'], ['CY', 'CY'], ['CZ', 'CZ'], ['DE', 'DE'], ['DJ', 'DJ'], ['DK', 'DK'],
                    ['DM', 'DM'], ['DO', 'DO'], ['DZ', 'DZ'], ['EC', 'EC'], ['EE', 'EE'], ['EG', 'EG'], ['EH', 'EH'], ['ER', 'ER'], ['ES', 'ES'], ['ET', 'ET'],
                    ['FI', 'FI'], ['FJ', 'FJ'], ['FK', 'FK'], ['FM', 'FM'], ['FO', 'FO'], ['FR', 'FR'], ['GA', 'GA'], ['GB', 'GB'], ['GD', 'GD'], ['GE', 'GE'],
                    ['GF', 'GF'], ['GG', 'GG'], ['GH', 'GH'], ['GI', 'GI'], ['GL', 'GL'], ['GM', 'GM'], ['GN', 'GN'], ['GP', 'GP'], ['GQ', 'GQ'], ['GR', 'GR'],
                    ['GS', 'GS'], ['GT', 'GT'], ['GU', 'GU'], ['GW', 'GW'], ['GY', 'GY'], ['HK', 'HK'], ['HM', 'HM'], ['HN', 'HN'], ['HR', 'HR'], ['HT', 'HT'],
                    ['HU', 'HU'], ['ID', 'ID'], ['IE', 'IE'], ['IL', 'IL'], ['IM', 'IM'], ['IN', 'IN'], ['IO', 'IO'], ['IQ', 'IQ'], ['IR', 'IR'], ['IS', 'IS'],
                    ['IT', 'IT'], ['JE', 'JE'], ['JM', 'JM'], ['JO', 'JO'], ['JP', 'JP'], ['KE', 'KE'], ['KG', 'KG'], ['KH', 'KH'], ['KI', 'KI'], ['KM', 'KM'],
                    ['KN', 'KN'], ['KP', 'KP'], ['KR', 'KR'], ['KW', 'KW'], ['KY', 'KY'], ['KZ', 'KZ'], ['LA', 'LA'], ['LB', 'LB'], ['LC', 'LC'], ['LI', 'LI'],
                    ['LK', 'LK'], ['LR', 'LR'], ['LS', 'LS'], ['LT', 'LT'], ['LU', 'LU'], ['LV', 'LV'], ['LY', 'LY'], ['MA', 'MA'], ['MC', 'MC'], ['MD', 'MD'],
                    ['ME', 'ME'], ['MF', 'MF'], ['MG', 'MG'], ['MH', 'MH'], ['MK', 'MK'], ['ML', 'ML'], ['MM', 'MM'], ['MN', 'MN'], ['MO', 'MO'], ['MP', 'MP'],
                    ['MQ', 'MQ'], ['MR', 'MR'], ['MS', 'MS'], ['MT', 'MT'], ['MU', 'MU'], ['MV', 'MV'], ['MW', 'MW'], ['MX', 'MX'], ['MY', 'MY'], ['MZ', 'MZ'],
                    ['NA', 'NA'], ['NC', 'NC'], ['NE', 'NE'], ['NF', 'NF'], ['NG', 'NG'], ['NI', 'NI'], ['NL', 'NL'], ['NO', 'NO'], ['NP', 'NP'], ['NR', 'NR'],
                    ['NU', 'NU'], ['NZ', 'NZ'], ['OM', 'OM'], ['PA', 'PA'], ['PE', 'PE'], ['PF', 'PF'], ['PG', 'PG'], ['PH', 'PH'], ['PK', 'PK'], ['PL', 'PL'],
                    ['PM', 'PM'], ['PN', 'PN'], ['PR', 'PR'], ['PS', 'PS'], ['PT', 'PT'], ['PW', 'PW'], ['PY', 'PY'], ['QA', 'QA'], ['RE', 'RE'], ['RO', 'RO'],
                    ['RS', 'RS'], ['RU', 'RU'], ['RW', 'RW'], ['SA', 'SA'], ['SB', 'SB'], ['SC', 'SC'], ['SD', 'SD'], ['SE', 'SE'], ['SG', 'SG'], ['SH', 'SH'],
                    ['SI', 'SI'], ['SJ', 'SJ'], ['SK', 'SK'], ['SL', 'SL'], ['SM', 'SM'], ['SN', 'SN'], ['SO', 'SO'], ['SR', 'SR'], ['SS', 'SS'], ['ST', 'ST'],
                    ['SV', 'SV'], ['SX', 'SX'], ['SY', 'SY'], ['SZ', 'SZ'], ['TC', 'TC'], ['TD', 'TD'], ['TF', 'TF'], ['TG', 'TG'], ['TH', 'TH'], ['TJ', 'TJ'],
                    ['TK', 'TK'], ['TL', 'TL'], ['TM', 'TM'], ['TN', 'TN'], ['TO', 'TO'], ['TR', 'TR'], ['TT', 'TT'], ['TV', 'TV'], ['TW', 'TW'], ['TZ', 'TZ'],
                    ['UA', 'UA'], ['UG', 'UG'], ['UM', 'UM'], ['US', 'US'], ['UY', 'UY'], ['UZ', 'UZ'], ['VA', 'VA'], ['VC', 'VC'], ['VE', 'VE'], ['VG', 'VG'],
                    ['VI', 'VI'], ['VN', 'VN'], ['VU', 'VU'], ['WF', 'WF'], ['WS', 'WS'], ['YE', 'YE'], ['YT', 'YT'], ['ZA', 'ZA'], ['ZM', 'ZM'], ['ZW', 'ZW']
                ],
                'default' => ''
            ]
        ],
        'parameter' => [
            'exclude' => false,
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.parameter',
            'description' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.parameter.description',
            'config' => [
                'type' => 'input',
                'eval' => 'trim,required,alphanum_x,nospace,unique',
                'default' => ''
            ]
        ],
        'flag' => [
            'exclude' => false,
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.flag',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'items' => [
                    ['', 0, ''],
                    ['multiple', 'multiple', 'flags-multiple'],
                    ['ad', 'ad', 'flags-ad'],
                    ['ae', 'ae', 'flags-ae'],
                    ['af', 'af', 'flags-af'],
                    ['ag', 'ag', 'flags-ag'],
                    ['ai', 'ai', 'flags-ai'],
                    ['al', 'al', 'flags-al'],
                    ['am', 'am', 'flags-am'],
                    ['an', 'an', 'flags-an'],
                    ['ao', 'ao', 'flags-ao'],
                    ['aq', 'aq', 'flags-aq'],
                    ['ar', 'ar', 'flags-ar'],
                    ['as', 'as', 'flags-as'],
                    ['at', 'at', 'flags-at'],
                    ['au', 'au', 'flags-au'],
                    ['aw', 'aw', 'flags-aw'],
                    ['ax', 'ax', 'flags-ax'],
                    ['az', 'az', 'flags-az'],
                    ['ba', 'ba', 'flags-ba'],
                    ['bb', 'bb', 'flags-bb'],
                    ['bd', 'bd', 'flags-bd'],
                    ['be', 'be', 'flags-be'],
                    ['bf', 'bf', 'flags-bf'],
                    ['bg', 'bg', 'flags-bg'],
                    ['bh', 'bh', 'flags-bh'],
                    ['bi', 'bi', 'flags-bi'],
                    ['bj', 'bj', 'flags-bj'],
                    ['bl', 'bl', 'flags-bl'],
                    ['bm', 'bm', 'flags-bm'],
                    ['bn', 'bn', 'flags-bn'],
                    ['bo', 'bo', 'flags-bo'],
                    ['bq', 'bq', 'flags-bq'],
                    ['br', 'br', 'flags-br'],
                    ['bs', 'bs', 'flags-bs'],
                    ['bt', 'bt', 'flags-bt'],
                    ['bv', 'bv', 'flags-bv'],
                    ['bw', 'bw', 'flags-bw'],
                    ['by', 'by', 'flags-by'],
                    ['bz', 'bz', 'flags-bz'],
                    ['ca', 'ca', 'flags-ca'],
                    ['catalonia', 'catalonia', 'flags-catalonia'],
                    ['cc', 'cc', 'flags-cc'],
                    ['cd', 'cd', 'flags-cd'],
                    ['cf', 'cf', 'flags-cf'],
                    ['cg', 'cg', 'flags-cg'],
                    ['ch', 'ch', 'flags-ch'],
                    ['ci', 'ci', 'flags-ci'],
                    ['ck', 'ck', 'flags-ck'],
                    ['cl', 'cl', 'flags-cl'],
                    ['cm', 'cm', 'flags-cm'],
                    ['cn', 'cn', 'flags-cn'],
                    ['co', 'co', 'flags-co'],
                    ['cr', 'cr', 'flags-cr'],
                    ['cs', 'cs', 'flags-cs'],
                    ['cu', 'cu', 'flags-cu'],
                    ['cv', 'cv', 'flags-cv'],
                    ['cw', 'cw', 'flags-cw'],
                    ['cx', 'cx', 'flags-cx'],
                    ['cy', 'cy', 'flags-cy'],
                    ['cz', 'cz', 'flags-cz'],
                    ['de', 'de', 'flags-de'],
                    ['dj', 'dj', 'flags-dj'],
                    ['dk', 'dk', 'flags-dk'],
                    ['dm', 'dm', 'flags-dm'],
                    ['do', 'do', 'flags-do'],
                    ['dz', 'dz', 'flags-dz'],
                    ['ec', 'ec', 'flags-ec'],
                    ['ee', 'ee', 'flags-ee'],
                    ['eg', 'eg', 'flags-eg'],
                    ['eh', 'eh', 'flags-eh'],
                    ['en-us-gb', 'en-us-gb', 'flags-en-us-gb'],
                    ['england', 'england', 'flags-gb-eng'],
                    ['er', 'er', 'flags-er'],
                    ['es', 'es', 'flags-es'],
                    ['et', 'et', 'flags-et'],
                    ['eu', 'eu', 'flags-eu'],
                    ['fi', 'fi', 'flags-fi'],
                    ['fj', 'fj', 'flags-fj'],
                    ['fk', 'fk', 'flags-fk'],
                    ['fm', 'fm', 'flags-fm'],
                    ['fo', 'fo', 'flags-fo'],
                    ['fr', 'fr', 'flags-fr'],
                    ['ga', 'ga', 'flags-ga'],
                    ['gb', 'gb', 'flags-gb'],
                    ['gd', 'gd', 'flags-gd'],
                    ['ge', 'ge', 'flags-ge'],
                    ['gf', 'gf', 'flags-gf'],
                    ['gg', 'gg', 'flags-gg'],
                    ['gh', 'gh', 'flags-gh'],
                    ['gi', 'gi', 'flags-gi'],
                    ['gl', 'gl', 'flags-gl'],
                    ['gm', 'gm', 'flags-gm'],
                    ['gn', 'gn', 'flags-gn'],
                    ['gp', 'gp', 'flags-gp'],
                    ['gq', 'gq', 'flags-gq'],
                    ['gr', 'gr', 'flags-gr'],
                    ['gs', 'gs', 'flags-gs'],
                    ['gt', 'gt', 'flags-gt'],
                    ['gu', 'gu', 'flags-gu'],
                    ['gw', 'gw', 'flags-gw'],
                    ['gy', 'gy', 'flags-gy'],
                    ['hk', 'hk', 'flags-hk'],
                    ['hm', 'hm', 'flags-hm'],
                    ['hn', 'hn', 'flags-hn'],
                    ['hr', 'hr', 'flags-hr'],
                    ['ht', 'ht', 'flags-ht'],
                    ['hu', 'hu', 'flags-hu'],
                    ['id', 'id', 'flags-id'],
                    ['ie', 'ie', 'flags-ie'],
                    ['il', 'il', 'flags-il'],
                    ['im', 'im', 'flags-im'],
                    ['in', 'in', 'flags-in'],
                    ['io', 'io', 'flags-io'],
                    ['iq', 'iq', 'flags-iq'],
                    ['ir', 'ir', 'flags-ir'],
                    ['is', 'is', 'flags-is'],
                    ['it', 'it', 'flags-it'],
                    ['jm', 'jm', 'flags-jm'],
                    ['jo', 'jo', 'flags-jo'],
                    ['jp', 'jp', 'flags-jp'],
                    ['ke', 'ke', 'flags-ke'],
                    ['kg', 'kg', 'flags-kg'],
                    ['kh', 'kh', 'flags-kh'],
                    ['ki', 'ki', 'flags-ki'],
                    ['kl', 'kl', 'flags-kl'],
                    ['km', 'km', 'flags-km'],
                    ['kn', 'kn', 'flags-kn'],
                    ['kp', 'kp', 'flags-kp'],
                    ['kr', 'kr', 'flags-kr'],
                    ['kw', 'kw', 'flags-kw'],
                    ['ky', 'ky', 'flags-ky'],
                    ['kz', 'kz', 'flags-kz'],
                    ['la', 'la', 'flags-la'],
                    ['lb', 'lb', 'flags-lb'],
                    ['lc', 'lc', 'flags-lc'],
                    ['li', 'li', 'flags-li'],
                    ['lk', 'lk', 'flags-lk'],
                    ['lr', 'lr', 'flags-lr'],
                    ['ls', 'ls', 'flags-ls'],
                    ['lt', 'lt', 'flags-lt'],
                    ['lu', 'lu', 'flags-lu'],
                    ['lv', 'lv', 'flags-lv'],
                    ['ly', 'ly', 'flags-ly'],
                    ['ma', 'ma', 'flags-ma'],
                    ['mc', 'mc', 'flags-mc'],
                    ['md', 'md', 'flags-md'],
                    ['me', 'me', 'flags-me'],
                    ['mf', 'mf', 'flags-mf'],
                    ['mg', 'mg', 'flags-mg'],
                    ['mh', 'mh', 'flags-mh'],
                    ['mi', 'mi', 'flags-mi'],
                    ['mk', 'mk', 'flags-mk'],
                    ['ml', 'ml', 'flags-ml'],
                    ['mm', 'mm', 'flags-mm'],
                    ['mn', 'mn', 'flags-mn'],
                    ['mo', 'mo', 'flags-mo'],
                    ['mp', 'mp', 'flags-mp'],
                    ['mq', 'mq', 'flags-mq'],
                    ['mr', 'mr', 'flags-mr'],
                    ['ms', 'ms', 'flags-ms'],
                    ['mt', 'mt', 'flags-mt'],
                    ['mu', 'mu', 'flags-mu'],
                    ['mv', 'mv', 'flags-mv'],
                    ['mw', 'mw', 'flags-mw'],
                    ['mx', 'mx', 'flags-mx'],
                    ['my', 'my', 'flags-my'],
                    ['mz', 'mz', 'flags-mz'],
                    ['na', 'na', 'flags-na'],
                    ['nc', 'nc', 'flags-nc'],
                    ['ne', 'ne', 'flags-ne'],
                    ['nf', 'nf', 'flags-nf'],
                    ['ng', 'ng', 'flags-ng'],
                    ['ni', 'ni', 'flags-ni'],
                    ['gb-nir', 'gb-nir', 'flags-gb-nir'],
                    ['nl', 'nl', 'flags-nl'],
                    ['no', 'no', 'flags-no'],
                    ['np', 'np', 'flags-np'],
                    ['nr', 'nr', 'flags-nr'],
                    ['nu', 'nu', 'flags-nu'],
                    ['nz', 'nz', 'flags-nz'],
                    ['om', 'om', 'flags-om'],
                    ['pa', 'pa', 'flags-pa'],
                    ['pe', 'pe', 'flags-pe'],
                    ['pf', 'pf', 'flags-pf'],
                    ['pg', 'pg', 'flags-pg'],
                    ['ph', 'ph', 'flags-ph'],
                    ['pk', 'pk', 'flags-pk'],
                    ['pl', 'pl', 'flags-pl'],
                    ['pm', 'pm', 'flags-pm'],
                    ['pn', 'pn', 'flags-pn'],
                    ['pr', 'pr', 'flags-pr'],
                    ['ps', 'ps', 'flags-ps'],
                    ['pt', 'pt', 'flags-pt'],
                    ['pw', 'pw', 'flags-pw'],
                    ['py', 'py', 'flags-py'],
                    ['qa', 'qa', 'flags-qa'],
                    ['qc', 'qc', 'flags-qc'],
                    ['re', 're', 'flags-re'],
                    ['ro', 'ro', 'flags-ro'],
                    ['rs', 'rs', 'flags-rs'],
                    ['ru', 'ru', 'flags-ru'],
                    ['rw', 'rw', 'flags-rw'],
                    ['sa', 'sa', 'flags-sa'],
                    ['sb', 'sb', 'flags-sb'],
                    ['sc', 'sc', 'flags-sc'],
                    ['gb-sct', 'gb-sct', 'flags-gb-sct'],
                    ['sd', 'sd', 'flags-sd'],
                    ['se', 'se', 'flags-se'],
                    ['sg', 'sg', 'flags-sg'],
                    ['sh', 'sh', 'flags-sh'],
                    ['si', 'si', 'flags-si'],
                    ['sj', 'sj', 'flags-sj'],
                    ['sk', 'sk', 'flags-sk'],
                    ['sl', 'sl', 'flags-sl'],
                    ['sm', 'sm', 'flags-sm'],
                    ['sn', 'sn', 'flags-sn'],
                    ['so', 'so', 'flags-so'],
                    ['sr', 'sr', 'flags-sr'],
                    ['ss', 'ss', 'flags-ss'],
                    ['st', 'st', 'flags-st'],
                    ['sv', 'sv', 'flags-sv'],
                    ['sx', 'sx', 'flags-sx'],
                    ['sy', 'sy', 'flags-sy'],
                    ['sz', 'sz', 'flags-sz'],
                    ['tc', 'tc', 'flags-tc'],
                    ['td', 'td', 'flags-td'],
                    ['tf', 'tf', 'flags-tf'],
                    ['tg', 'tg', 'flags-tg'],
                    ['th', 'th', 'flags-th'],
                    ['tj', 'tj', 'flags-tj'],
                    ['tk', 'tk', 'flags-tk'],
                    ['tl', 'tl', 'flags-tl'],
                    ['tm', 'tm', 'flags-tm'],
                    ['tn', 'tn', 'flags-tn'],
                    ['to', 'to', 'flags-to'],
                    ['tr', 'tr', 'flags-tr'],
                    ['tt', 'tt', 'flags-tt'],
                    ['tv', 'tv', 'flags-tv'],
                    ['tw', 'tw', 'flags-tw'],
                    ['tz', 'tz', 'flags-tz'],
                    ['ua', 'ua', 'flags-ua'],
                    ['ug', 'ug', 'flags-ug'],
                    ['um', 'um', 'flags-um'],
                    ['us', 'us', 'flags-us'],
                    ['uy', 'uy', 'flags-uy'],
                    ['uz', 'uz', 'flags-uz'],
                    ['va', 'va', 'flags-va'],
                    ['vc', 'vc', 'flags-vc'],
                    ['ve', 've', 'flags-ve'],
                    ['vg', 'vg', 'flags-vg'],
                    ['vi', 'vi', 'flags-vi'],
                    ['vn', 'vn', 'flags-vn'],
                    ['vu', 'vu', 'flags-vu'],
                    ['gb-wls', 'gb-wls', 'flags-gb-wls'],
                    ['wf', 'wf', 'flags-wf'],
                    ['ws', 'ws', 'flags-ws'],
                    ['ye', 'ye', 'flags-ye'],
                    ['yt', 'yt', 'flags-yt'],
                    ['za', 'za', 'flags-za'],
                    ['zm', 'zm', 'flags-zm'],
                    ['zw', 'zw', 'flags-zw']
                ],
                'maxitems' => 1
            ]
        ]
    ]
];
