<?php

return [
    'ctrl' => [
        'title' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country',
        'label' => 'title',
        'default_sortby' => 'title',
        'tstamp' => 'tstamp',
        'crdate' => 'crdate',
        'delete' => 'deleted',
        'rootLevel' => 1,
        'adminOnly' => true,
        'enablecolumns' => [
            'disabled' => 'hidden'
        ],
        'searchFields' => 'title, iso_code',
        'typeicon_classes' => [
            'default' => 'flags-multiple',
            'mask' => 'flags-###TYPE###'
        ],
        'typeicon_column' => 'flag'
    ],
    'palettes' => [
        'visibility' => [
            'showitem' => 'hidden, enabled',
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.palette.visibility'
        ]
    ],
    'types' => [
        '1' => [
            'showitem' => '--palette--;;visibility, title, iso_code, parameter, flag'
        ]
    ],
    'columns' => [
        'hidden' => [
            'exclude' => true,
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.hidden',
            'config' => [
                'type' => 'check',
                'items' => [
                    ['label' => '', 'invertStateDisplay' => true]
                ],
                'default' => 0
            ]
        ],
        'enabled' => [
            'exclude' => true,
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.enabled',
            'config' => [
                'type' => 'check',
                'items' => [
                    ['label' => '']
                ],
                'default' => 1
            ]
        ],
        'title' => [
            'exclude' => false,
            'l10n_mode' => 'exclude',
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.title',
            'config' => [
                'type' => 'input',
                'eval' => 'trim',
                'default' => '',
                'required' => true
            ]
        ],
        'iso_code' => [
            'exclude' => false,
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.iso_code',
            'description' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.iso_code.description',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'eval' => 'trim,unique',
                'max' => 2,
                'items' => [
                    ['label' => '----', 'value' => ''], ['label' => 'AD', 'value' => 'AD'], ['label' => 'AE', 'value' => 'AE'], ['label' => 'AF', 'value' => 'AF'], ['label' => 'AG', 'value' => 'AG'], ['label' => 'AI', 'value' => 'AI'], ['label' => 'AL', 'value' => 'AL'], ['label' => 'AM', 'value' => 'AM'], ['label' => 'AO', 'value' => 'AO'], ['label' => 'AQ', 'value' => 'AQ'],
                    ['label' => 'AR', 'value' => 'AR'], ['label' => 'AS', 'value' => 'AS'], ['label' => 'AT', 'value' => 'AT'], ['label' => 'AU', 'value' => 'AU'], ['label' => 'AW', 'value' => 'AW'], ['label' => 'AX', 'value' => 'AX'], ['label' => 'AZ', 'value' => 'AZ'], ['label' => 'BA', 'value' => 'BA'], ['label' => 'BB', 'value' => 'BB'], ['label' => 'BD', 'value' => 'BD'],
                    ['label' => 'BE', 'value' => 'BE'], ['label' => 'BF', 'value' => 'BF'], ['label' => 'BG', 'value' => 'BG'], ['label' => 'BH', 'value' => 'BH'], ['label' => 'BI', 'value' => 'BI'], ['label' => 'BJ', 'value' => 'BJ'], ['label' => 'BL', 'value' => 'BL'], ['label' => 'BM', 'value' => 'BM'], ['label' => 'BN', 'value' => 'BN'], ['label' => 'BO', 'value' => 'BO'],
                    ['label' => 'BQ', 'value' => 'BQ'], ['label' => 'BR', 'value' => 'BR'], ['label' => 'BS', 'value' => 'BS'], ['label' => 'BT', 'value' => 'BT'], ['label' => 'BV', 'value' => 'BV'], ['label' => 'BW', 'value' => 'BW'], ['label' => 'BY', 'value' => 'BY'], ['label' => 'BZ', 'value' => 'BZ'], ['label' => 'CA', 'value' => 'CA'], ['label' => 'CC', 'value' => 'CC'],
                    ['label' => 'CD', 'value' => 'CD'], ['label' => 'CF', 'value' => 'CF'], ['label' => 'CG', 'value' => 'CG'], ['label' => 'CH', 'value' => 'CH'], ['label' => 'CI', 'value' => 'CI'], ['label' => 'CK', 'value' => 'CK'], ['label' => 'CL', 'value' => 'CL'], ['label' => 'CM', 'value' => 'CM'], ['label' => 'CN', 'value' => 'CN'], ['label' => 'CO', 'value' => 'CO'],
                    ['label' => 'CR', 'value' => 'CR'], ['label' => 'CU', 'value' => 'CU'], ['label' => 'CV', 'value' => 'CV'], ['label' => 'CW', 'value' => 'CW'], ['label' => 'CX', 'value' => 'CX'], ['label' => 'CY', 'value' => 'CY'], ['label' => 'CZ', 'value' => 'CZ'], ['label' => 'DE', 'value' => 'DE'], ['label' => 'DJ', 'value' => 'DJ'], ['label' => 'DK', 'value' => 'DK'],
                    ['label' => 'DM', 'value' => 'DM'], ['label' => 'DO', 'value' => 'DO'], ['label' => 'DZ', 'value' => 'DZ'], ['label' => 'EC', 'value' => 'EC'], ['label' => 'EE', 'value' => 'EE'], ['label' => 'EG', 'value' => 'EG'], ['label' => 'EH', 'value' => 'EH'], ['label' => 'ER', 'value' => 'ER'], ['label' => 'ES', 'value' => 'ES'], ['label' => 'ET', 'value' => 'ET'],
                    ['label' => 'FI', 'value' => 'FI'], ['label' => 'FJ', 'value' => 'FJ'], ['label' => 'FK', 'value' => 'FK'], ['label' => 'FM', 'value' => 'FM'], ['label' => 'FO', 'value' => 'FO'], ['label' => 'FR', 'value' => 'FR'], ['label' => 'GA', 'value' => 'GA'], ['label' => 'GB', 'value' => 'GB'], ['label' => 'GD', 'value' => 'GD'], ['label' => 'GE', 'value' => 'GE'],
                    ['label' => 'GF', 'value' => 'GF'], ['label' => 'GG', 'value' => 'GG'], ['label' => 'GH', 'value' => 'GH'], ['label' => 'GI', 'value' => 'GI'], ['label' => 'GL', 'value' => 'GL'], ['label' => 'GM', 'value' => 'GM'], ['label' => 'GN', 'value' => 'GN'], ['label' => 'GP', 'value' => 'GP'], ['label' => 'GQ', 'value' => 'GQ'], ['label' => 'GR', 'value' => 'GR'],
                    ['label' => 'GS', 'value' => 'GS'], ['label' => 'GT', 'value' => 'GT'], ['label' => 'GU', 'value' => 'GU'], ['label' => 'GW', 'value' => 'GW'], ['label' => 'GY', 'value' => 'GY'], ['label' => 'HK', 'value' => 'HK'], ['label' => 'HM', 'value' => 'HM'], ['label' => 'HN', 'value' => 'HN'], ['label' => 'HR', 'value' => 'HR'], ['label' => 'HT', 'value' => 'HT'],
                    ['label' => 'HU', 'value' => 'HU'], ['label' => 'ID', 'value' => 'ID'], ['label' => 'IE', 'value' => 'IE'], ['label' => 'IL', 'value' => 'IL'], ['label' => 'IM', 'value' => 'IM'], ['label' => 'IN', 'value' => 'IN'], ['label' => 'IO', 'value' => 'IO'], ['label' => 'IQ', 'value' => 'IQ'], ['label' => 'IR', 'value' => 'IR'], ['label' => 'IS', 'value' => 'IS'],
                    ['label' => 'IT', 'value' => 'IT'], ['label' => 'JE', 'value' => 'JE'], ['label' => 'JM', 'value' => 'JM'], ['label' => 'JO', 'value' => 'JO'], ['label' => 'JP', 'value' => 'JP'], ['label' => 'KE', 'value' => 'KE'], ['label' => 'KG', 'value' => 'KG'], ['label' => 'KH', 'value' => 'KH'], ['label' => 'KI', 'value' => 'KI'], ['label' => 'KM', 'value' => 'KM'],
                    ['label' => 'KN', 'value' => 'KN'], ['label' => 'KP', 'value' => 'KP'], ['label' => 'KR', 'value' => 'KR'], ['label' => 'KW', 'value' => 'KW'], ['label' => 'KY', 'value' => 'KY'], ['label' => 'KZ', 'value' => 'KZ'], ['label' => 'LA', 'value' => 'LA'], ['label' => 'LB', 'value' => 'LB'], ['label' => 'LC', 'value' => 'LC'], ['label' => 'LI', 'value' => 'LI'],
                    ['label' => 'LK', 'value' => 'LK'], ['label' => 'LR', 'value' => 'LR'], ['label' => 'LS', 'value' => 'LS'], ['label' => 'LT', 'value' => 'LT'], ['label' => 'LU', 'value' => 'LU'], ['label' => 'LV', 'value' => 'LV'], ['label' => 'LY', 'value' => 'LY'], ['label' => 'MA', 'value' => 'MA'], ['label' => 'MC', 'value' => 'MC'], ['label' => 'MD', 'value' => 'MD'],
                    ['label' => 'ME', 'value' => 'ME'], ['label' => 'MF', 'value' => 'MF'], ['label' => 'MG', 'value' => 'MG'], ['label' => 'MH', 'value' => 'MH'], ['label' => 'MK', 'value' => 'MK'], ['label' => 'ML', 'value' => 'ML'], ['label' => 'MM', 'value' => 'MM'], ['label' => 'MN', 'value' => 'MN'], ['label' => 'MO', 'value' => 'MO'], ['label' => 'MP', 'value' => 'MP'],
                    ['label' => 'MQ', 'value' => 'MQ'], ['label' => 'MR', 'value' => 'MR'], ['label' => 'MS', 'value' => 'MS'], ['label' => 'MT', 'value' => 'MT'], ['label' => 'MU', 'value' => 'MU'], ['label' => 'MV', 'value' => 'MV'], ['label' => 'MW', 'value' => 'MW'], ['label' => 'MX', 'value' => 'MX'], ['label' => 'MY', 'value' => 'MY'], ['label' => 'MZ', 'value' => 'MZ'],
                    ['label' => 'NA', 'value' => 'NA'], ['label' => 'NC', 'value' => 'NC'], ['label' => 'NE', 'value' => 'NE'], ['label' => 'NF', 'value' => 'NF'], ['label' => 'NG', 'value' => 'NG'], ['label' => 'NI', 'value' => 'NI'], ['label' => 'NL', 'value' => 'NL'], ['label' => 'NO', 'value' => 'NO'], ['label' => 'NP', 'value' => 'NP'], ['label' => 'NR', 'value' => 'NR'],
                    ['label' => 'NU', 'value' => 'NU'], ['label' => 'NZ', 'value' => 'NZ'], ['label' => 'OM', 'value' => 'OM'], ['label' => 'PA', 'value' => 'PA'], ['label' => 'PE', 'value' => 'PE'], ['label' => 'PF', 'value' => 'PF'], ['label' => 'PG', 'value' => 'PG'], ['label' => 'PH', 'value' => 'PH'], ['label' => 'PK', 'value' => 'PK'], ['label' => 'PL', 'value' => 'PL'],
                    ['label' => 'PM', 'value' => 'PM'], ['label' => 'PN', 'value' => 'PN'], ['label' => 'PR', 'value' => 'PR'], ['label' => 'PS', 'value' => 'PS'], ['label' => 'PT', 'value' => 'PT'], ['label' => 'PW', 'value' => 'PW'], ['label' => 'PY', 'value' => 'PY'], ['label' => 'QA', 'value' => 'QA'], ['label' => 'RE', 'value' => 'RE'], ['label' => 'RO', 'value' => 'RO'],
                    ['label' => 'RS', 'value' => 'RS'], ['label' => 'RU', 'value' => 'RU'], ['label' => 'RW', 'value' => 'RW'], ['label' => 'SA', 'value' => 'SA'], ['label' => 'SB', 'value' => 'SB'], ['label' => 'SC', 'value' => 'SC'], ['label' => 'SD', 'value' => 'SD'], ['label' => 'SE', 'value' => 'SE'], ['label' => 'SG', 'value' => 'SG'], ['label' => 'SH', 'value' => 'SH'],
                    ['label' => 'SI', 'value' => 'SI'], ['label' => 'SJ', 'value' => 'SJ'], ['label' => 'SK', 'value' => 'SK'], ['label' => 'SL', 'value' => 'SL'], ['label' => 'SM', 'value' => 'SM'], ['label' => 'SN', 'value' => 'SN'], ['label' => 'SO', 'value' => 'SO'], ['label' => 'SR', 'value' => 'SR'], ['label' => 'SS', 'value' => 'SS'], ['label' => 'ST', 'value' => 'ST'],
                    ['label' => 'SV', 'value' => 'SV'], ['label' => 'SX', 'value' => 'SX'], ['label' => 'SY', 'value' => 'SY'], ['label' => 'SZ', 'value' => 'SZ'], ['label' => 'TC', 'value' => 'TC'], ['label' => 'TD', 'value' => 'TD'], ['label' => 'TF', 'value' => 'TF'], ['label' => 'TG', 'value' => 'TG'], ['label' => 'TH', 'value' => 'TH'], ['label' => 'TJ', 'value' => 'TJ'],
                    ['label' => 'TK', 'value' => 'TK'], ['label' => 'TL', 'value' => 'TL'], ['label' => 'TM', 'value' => 'TM'], ['label' => 'TN', 'value' => 'TN'], ['label' => 'TO', 'value' => 'TO'], ['label' => 'TR', 'value' => 'TR'], ['label' => 'TT', 'value' => 'TT'], ['label' => 'TV', 'value' => 'TV'], ['label' => 'TW', 'value' => 'TW'], ['label' => 'TZ', 'value' => 'TZ'],
                    ['label' => 'UA', 'value' => 'UA'], ['label' => 'UG', 'value' => 'UG'], ['label' => 'UM', 'value' => 'UM'], ['label' => 'US', 'value' => 'US'], ['label' => 'UY', 'value' => 'UY'], ['label' => 'UZ', 'value' => 'UZ'], ['label' => 'VA', 'value' => 'VA'], ['label' => 'VC', 'value' => 'VC'], ['label' => 'VE', 'value' => 'VE'], ['label' => 'VG', 'value' => 'VG'],
                    ['label' => 'VI', 'value' => 'VI'], ['label' => 'VN', 'value' => 'VN'], ['label' => 'VU', 'value' => 'VU'], ['label' => 'WF', 'value' => 'WF'], ['label' => 'WS', 'value' => 'WS'], ['label' => 'YE', 'value' => 'YE'], ['label' => 'YT', 'value' => 'YT'], ['label' => 'ZA', 'value' => 'ZA'], ['label' => 'ZM', 'value' => 'ZM'], ['label' => 'ZW', 'value' => 'ZW']
                ],
                'default' => '',
                'required' => true
            ]
        ],
        'parameter' => [
            'exclude' => false,
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.parameter',
            'description' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.parameter.description',
            'config' => [
                'type' => 'input',
                'eval' => 'trim,alphanum_x,nospace,unique',
                'default' => '',
                'required' => true
            ]
        ],
        'flag' => [
            'exclude' => false,
            'label' => 'LLL:EXT:z7_countries/Resources/Private/Language/locallang_db.xlf:tx_z7countries_country.flag',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'items' => [
                    ['label' => '', 'value' => 0, 'icon' => ''],
                    ['label' => 'multiple', 'value' => 'multiple', 'icon' => 'flags-multiple'],
                    ['label' => 'ad', 'value' => 'ad', 'icon' => 'flags-ad'],
                    ['label' => 'ae', 'value' => 'ae', 'icon' => 'flags-ae'],
                    ['label' => 'af', 'value' => 'af', 'icon' => 'flags-af'],
                    ['label' => 'ag', 'value' => 'ag', 'icon' => 'flags-ag'],
                    ['label' => 'ai', 'value' => 'ai', 'icon' => 'flags-ai'],
                    ['label' => 'al', 'value' => 'al', 'icon' => 'flags-al'],
                    ['label' => 'am', 'value' => 'am', 'icon' => 'flags-am'],
                    ['label' => 'an', 'value' => 'an', 'icon' => 'flags-an'],
                    ['label' => 'ao', 'value' => 'ao', 'icon' => 'flags-ao'],
                    ['label' => 'aq', 'value' => 'aq', 'icon' => 'flags-aq'],
                    ['label' => 'ar', 'value' => 'ar', 'icon' => 'flags-ar'],
                    ['label' => 'as', 'value' => 'as', 'icon' => 'flags-as'],
                    ['label' => 'at', 'value' => 'at', 'icon' => 'flags-at'],
                    ['label' => 'au', 'value' => 'au', 'icon' => 'flags-au'],
                    ['label' => 'aw', 'value' => 'aw', 'icon' => 'flags-aw'],
                    ['label' => 'ax', 'value' => 'ax', 'icon' => 'flags-ax'],
                    ['label' => 'az', 'value' => 'az', 'icon' => 'flags-az'],
                    ['label' => 'ba', 'value' => 'ba', 'icon' => 'flags-ba'],
                    ['label' => 'bb', 'value' => 'bb', 'icon' => 'flags-bb'],
                    ['label' => 'bd', 'value' => 'bd', 'icon' => 'flags-bd'],
                    ['label' => 'be', 'value' => 'be', 'icon' => 'flags-be'],
                    ['label' => 'bf', 'value' => 'bf', 'icon' => 'flags-bf'],
                    ['label' => 'bg', 'value' => 'bg', 'icon' => 'flags-bg'],
                    ['label' => 'bh', 'value' => 'bh', 'icon' => 'flags-bh'],
                    ['label' => 'bi', 'value' => 'bi', 'icon' => 'flags-bi'],
                    ['label' => 'bj', 'value' => 'bj', 'icon' => 'flags-bj'],
                    ['label' => 'bl', 'value' => 'bl', 'icon' => 'flags-bl'],
                    ['label' => 'bm', 'value' => 'bm', 'icon' => 'flags-bm'],
                    ['label' => 'bn', 'value' => 'bn', 'icon' => 'flags-bn'],
                    ['label' => 'bo', 'value' => 'bo', 'icon' => 'flags-bo'],
                    ['label' => 'bq', 'value' => 'bq', 'icon' => 'flags-bq'],
                    ['label' => 'br', 'value' => 'br', 'icon' => 'flags-br'],
                    ['label' => 'bs', 'value' => 'bs', 'icon' => 'flags-bs'],
                    ['label' => 'bt', 'value' => 'bt', 'icon' => 'flags-bt'],
                    ['label' => 'bv', 'value' => 'bv', 'icon' => 'flags-bv'],
                    ['label' => 'bw', 'value' => 'bw', 'icon' => 'flags-bw'],
                    ['label' => 'by', 'value' => 'by', 'icon' => 'flags-by'],
                    ['label' => 'bz', 'value' => 'bz', 'icon' => 'flags-bz'],
                    ['label' => 'ca', 'value' => 'ca', 'icon' => 'flags-ca'],
                    ['label' => 'catalonia', 'value' => 'catalonia', 'icon' => 'flags-catalonia'],
                    ['label' => 'cc', 'value' => 'cc', 'icon' => 'flags-cc'],
                    ['label' => 'cd', 'value' => 'cd', 'icon' => 'flags-cd'],
                    ['label' => 'cf', 'value' => 'cf', 'icon' => 'flags-cf'],
                    ['label' => 'cg', 'value' => 'cg', 'icon' => 'flags-cg'],
                    ['label' => 'ch', 'value' => 'ch', 'icon' => 'flags-ch'],
                    ['label' => 'ci', 'value' => 'ci', 'icon' => 'flags-ci'],
                    ['label' => 'ck', 'value' => 'ck', 'icon' => 'flags-ck'],
                    ['label' => 'cl', 'value' => 'cl', 'icon' => 'flags-cl'],
                    ['label' => 'cm', 'value' => 'cm', 'icon' => 'flags-cm'],
                    ['label' => 'cn', 'value' => 'cn', 'icon' => 'flags-cn'],
                    ['label' => 'co', 'value' => 'co', 'icon' => 'flags-co'],
                    ['label' => 'cr', 'value' => 'cr', 'icon' => 'flags-cr'],
                    ['label' => 'cs', 'value' => 'cs', 'icon' => 'flags-cs'],
                    ['label' => 'cu', 'value' => 'cu', 'icon' => 'flags-cu'],
                    ['label' => 'cv', 'value' => 'cv', 'icon' => 'flags-cv'],
                    ['label' => 'cw', 'value' => 'cw', 'icon' => 'flags-cw'],
                    ['label' => 'cx', 'value' => 'cx', 'icon' => 'flags-cx'],
                    ['label' => 'cy', 'value' => 'cy', 'icon' => 'flags-cy'],
                    ['label' => 'cz', 'value' => 'cz', 'icon' => 'flags-cz'],
                    ['label' => 'de', 'value' => 'de', 'icon' => 'flags-de'],
                    ['label' => 'dj', 'value' => 'dj', 'icon' => 'flags-dj'],
                    ['label' => 'dk', 'value' => 'dk', 'icon' => 'flags-dk'],
                    ['label' => 'dm', 'value' => 'dm', 'icon' => 'flags-dm'],
                    ['label' => 'do', 'value' => 'do', 'icon' => 'flags-do'],
                    ['label' => 'dz', 'value' => 'dz', 'icon' => 'flags-dz'],
                    ['label' => 'ec', 'value' => 'ec', 'icon' => 'flags-ec'],
                    ['label' => 'ee', 'value' => 'ee', 'icon' => 'flags-ee'],
                    ['label' => 'eg', 'value' => 'eg', 'icon' => 'flags-eg'],
                    ['label' => 'eh', 'value' => 'eh', 'icon' => 'flags-eh'],
                    ['label' => 'en-us-gb', 'value' => 'en-us-gb', 'icon' => 'flags-en-us-gb'],
                    ['label' => 'england', 'value' => 'england', 'icon' => 'flags-gb-eng'],
                    ['label' => 'er', 'value' => 'er', 'icon' => 'flags-er'],
                    ['label' => 'es', 'value' => 'es', 'icon' => 'flags-es'],
                    ['label' => 'et', 'value' => 'et', 'icon' => 'flags-et'],
                    ['label' => 'eu', 'value' => 'eu', 'icon' => 'flags-eu'],
                    ['label' => 'fi', 'value' => 'fi', 'icon' => 'flags-fi'],
                    ['label' => 'fj', 'value' => 'fj', 'icon' => 'flags-fj'],
                    ['label' => 'fk', 'value' => 'fk', 'icon' => 'flags-fk'],
                    ['label' => 'fm', 'value' => 'fm', 'icon' => 'flags-fm'],
                    ['label' => 'fo', 'value' => 'fo', 'icon' => 'flags-fo'],
                    ['label' => 'fr', 'value' => 'fr', 'icon' => 'flags-fr'],
                    ['label' => 'ga', 'value' => 'ga', 'icon' => 'flags-ga'],
                    ['label' => 'gb', 'value' => 'gb', 'icon' => 'flags-gb'],
                    ['label' => 'gd', 'value' => 'gd', 'icon' => 'flags-gd'],
                    ['label' => 'ge', 'value' => 'ge', 'icon' => 'flags-ge'],
                    ['label' => 'gf', 'value' => 'gf', 'icon' => 'flags-gf'],
                    ['label' => 'gg', 'value' => 'gg', 'icon' => 'flags-gg'],
                    ['label' => 'gh', 'value' => 'gh', 'icon' => 'flags-gh'],
                    ['label' => 'gi', 'value' => 'gi', 'icon' => 'flags-gi'],
                    ['label' => 'gl', 'value' => 'gl', 'icon' => 'flags-gl'],
                    ['label' => 'gm', 'value' => 'gm', 'icon' => 'flags-gm'],
                    ['label' => 'gn', 'value' => 'gn', 'icon' => 'flags-gn'],
                    ['label' => 'gp', 'value' => 'gp', 'icon' => 'flags-gp'],
                    ['label' => 'gq', 'value' => 'gq', 'icon' => 'flags-gq'],
                    ['label' => 'gr', 'value' => 'gr', 'icon' => 'flags-gr'],
                    ['label' => 'gs', 'value' => 'gs', 'icon' => 'flags-gs'],
                    ['label' => 'gt', 'value' => 'gt', 'icon' => 'flags-gt'],
                    ['label' => 'gu', 'value' => 'gu', 'icon' => 'flags-gu'],
                    ['label' => 'gw', 'value' => 'gw', 'icon' => 'flags-gw'],
                    ['label' => 'gy', 'value' => 'gy', 'icon' => 'flags-gy'],
                    ['label' => 'hk', 'value' => 'hk', 'icon' => 'flags-hk'],
                    ['label' => 'hm', 'value' => 'hm', 'icon' => 'flags-hm'],
                    ['label' => 'hn', 'value' => 'hn', 'icon' => 'flags-hn'],
                    ['label' => 'hr', 'value' => 'hr', 'icon' => 'flags-hr'],
                    ['label' => 'ht', 'value' => 'ht', 'icon' => 'flags-ht'],
                    ['label' => 'hu', 'value' => 'hu', 'icon' => 'flags-hu'],
                    ['label' => 'id', 'value' => 'id', 'icon' => 'flags-id'],
                    ['label' => 'ie', 'value' => 'ie', 'icon' => 'flags-ie'],
                    ['label' => 'il', 'value' => 'il', 'icon' => 'flags-il'],
                    ['label' => 'im', 'value' => 'im', 'icon' => 'flags-im'],
                    ['label' => 'in', 'value' => 'in', 'icon' => 'flags-in'],
                    ['label' => 'io', 'value' => 'io', 'icon' => 'flags-io'],
                    ['label' => 'iq', 'value' => 'iq', 'icon' => 'flags-iq'],
                    ['label' => 'ir', 'value' => 'ir', 'icon' => 'flags-ir'],
                    ['label' => 'is', 'value' => 'is', 'icon' => 'flags-is'],
                    ['label' => 'it', 'value' => 'it', 'icon' => 'flags-it'],
                    ['label' => 'jm', 'value' => 'jm', 'icon' => 'flags-jm'],
                    ['label' => 'jo', 'value' => 'jo', 'icon' => 'flags-jo'],
                    ['label' => 'jp', 'value' => 'jp', 'icon' => 'flags-jp'],
                    ['label' => 'ke', 'value' => 'ke', 'icon' => 'flags-ke'],
                    ['label' => 'kg', 'value' => 'kg', 'icon' => 'flags-kg'],
                    ['label' => 'kh', 'value' => 'kh', 'icon' => 'flags-kh'],
                    ['label' => 'ki', 'value' => 'ki', 'icon' => 'flags-ki'],
                    ['label' => 'kl', 'value' => 'kl', 'icon' => 'flags-kl'],
                    ['label' => 'km', 'value' => 'km', 'icon' => 'flags-km'],
                    ['label' => 'kn', 'value' => 'kn', 'icon' => 'flags-kn'],
                    ['label' => 'kp', 'value' => 'kp', 'icon' => 'flags-kp'],
                    ['label' => 'kr', 'value' => 'kr', 'icon' => 'flags-kr'],
                    ['label' => 'kw', 'value' => 'kw', 'icon' => 'flags-kw'],
                    ['label' => 'ky', 'value' => 'ky', 'icon' => 'flags-ky'],
                    ['label' => 'kz', 'value' => 'kz', 'icon' => 'flags-kz'],
                    ['label' => 'la', 'value' => 'la', 'icon' => 'flags-la'],
                    ['label' => 'lb', 'value' => 'lb', 'icon' => 'flags-lb'],
                    ['label' => 'lc', 'value' => 'lc', 'icon' => 'flags-lc'],
                    ['label' => 'li', 'value' => 'li', 'icon' => 'flags-li'],
                    ['label' => 'lk', 'value' => 'lk', 'icon' => 'flags-lk'],
                    ['label' => 'lr', 'value' => 'lr', 'icon' => 'flags-lr'],
                    ['label' => 'ls', 'value' => 'ls', 'icon' => 'flags-ls'],
                    ['label' => 'lt', 'value' => 'lt', 'icon' => 'flags-lt'],
                    ['label' => 'lu', 'value' => 'lu', 'icon' => 'flags-lu'],
                    ['label' => 'lv', 'value' => 'lv', 'icon' => 'flags-lv'],
                    ['label' => 'ly', 'value' => 'ly', 'icon' => 'flags-ly'],
                    ['label' => 'ma', 'value' => 'ma', 'icon' => 'flags-ma'],
                    ['label' => 'mc', 'value' => 'mc', 'icon' => 'flags-mc'],
                    ['label' => 'md', 'value' => 'md', 'icon' => 'flags-md'],
                    ['label' => 'me', 'value' => 'me', 'icon' => 'flags-me'],
                    ['label' => 'mf', 'value' => 'mf', 'icon' => 'flags-mf'],
                    ['label' => 'mg', 'value' => 'mg', 'icon' => 'flags-mg'],
                    ['label' => 'mh', 'value' => 'mh', 'icon' => 'flags-mh'],
                    ['label' => 'mi', 'value' => 'mi', 'icon' => 'flags-mi'],
                    ['label' => 'mk', 'value' => 'mk', 'icon' => 'flags-mk'],
                    ['label' => 'ml', 'value' => 'ml', 'icon' => 'flags-ml'],
                    ['label' => 'mm', 'value' => 'mm', 'icon' => 'flags-mm'],
                    ['label' => 'mn', 'value' => 'mn', 'icon' => 'flags-mn'],
                    ['label' => 'mo', 'value' => 'mo', 'icon' => 'flags-mo'],
                    ['label' => 'mp', 'value' => 'mp', 'icon' => 'flags-mp'],
                    ['label' => 'mq', 'value' => 'mq', 'icon' => 'flags-mq'],
                    ['label' => 'mr', 'value' => 'mr', 'icon' => 'flags-mr'],
                    ['label' => 'ms', 'value' => 'ms', 'icon' => 'flags-ms'],
                    ['label' => 'mt', 'value' => 'mt', 'icon' => 'flags-mt'],
                    ['label' => 'mu', 'value' => 'mu', 'icon' => 'flags-mu'],
                    ['label' => 'mv', 'value' => 'mv', 'icon' => 'flags-mv'],
                    ['label' => 'mw', 'value' => 'mw', 'icon' => 'flags-mw'],
                    ['label' => 'mx', 'value' => 'mx', 'icon' => 'flags-mx'],
                    ['label' => 'my', 'value' => 'my', 'icon' => 'flags-my'],
                    ['label' => 'mz', 'value' => 'mz', 'icon' => 'flags-mz'],
                    ['label' => 'na', 'value' => 'na', 'icon' => 'flags-na'],
                    ['label' => 'nc', 'value' => 'nc', 'icon' => 'flags-nc'],
                    ['label' => 'ne', 'value' => 'ne', 'icon' => 'flags-ne'],
                    ['label' => 'nf', 'value' => 'nf', 'icon' => 'flags-nf'],
                    ['label' => 'ng', 'value' => 'ng', 'icon' => 'flags-ng'],
                    ['label' => 'ni', 'value' => 'ni', 'icon' => 'flags-ni'],
                    ['label' => 'gb-nir', 'value' => 'gb-nir', 'icon' => 'flags-gb-nir'],
                    ['label' => 'nl', 'value' => 'nl', 'icon' => 'flags-nl'],
                    ['label' => 'no', 'value' => 'no', 'icon' => 'flags-no'],
                    ['label' => 'np', 'value' => 'np', 'icon' => 'flags-np'],
                    ['label' => 'nr', 'value' => 'nr', 'icon' => 'flags-nr'],
                    ['label' => 'nu', 'value' => 'nu', 'icon' => 'flags-nu'],
                    ['label' => 'nz', 'value' => 'nz', 'icon' => 'flags-nz'],
                    ['label' => 'om', 'value' => 'om', 'icon' => 'flags-om'],
                    ['label' => 'pa', 'value' => 'pa', 'icon' => 'flags-pa'],
                    ['label' => 'pe', 'value' => 'pe', 'icon' => 'flags-pe'],
                    ['label' => 'pf', 'value' => 'pf', 'icon' => 'flags-pf'],
                    ['label' => 'pg', 'value' => 'pg', 'icon' => 'flags-pg'],
                    ['label' => 'ph', 'value' => 'ph', 'icon' => 'flags-ph'],
                    ['label' => 'pk', 'value' => 'pk', 'icon' => 'flags-pk'],
                    ['label' => 'pl', 'value' => 'pl', 'icon' => 'flags-pl'],
                    ['label' => 'pm', 'value' => 'pm', 'icon' => 'flags-pm'],
                    ['label' => 'pn', 'value' => 'pn', 'icon' => 'flags-pn'],
                    ['label' => 'pr', 'value' => 'pr', 'icon' => 'flags-pr'],
                    ['label' => 'ps', 'value' => 'ps', 'icon' => 'flags-ps'],
                    ['label' => 'pt', 'value' => 'pt', 'icon' => 'flags-pt'],
                    ['label' => 'pw', 'value' => 'pw', 'icon' => 'flags-pw'],
                    ['label' => 'py', 'value' => 'py', 'icon' => 'flags-py'],
                    ['label' => 'qa', 'value' => 'qa', 'icon' => 'flags-qa'],
                    ['label' => 'qc', 'value' => 'qc', 'icon' => 'flags-qc'],
                    ['label' => 're', 'value' => 're', 'icon' => 'flags-re'],
                    ['label' => 'ro', 'value' => 'ro', 'icon' => 'flags-ro'],
                    ['label' => 'rs', 'value' => 'rs', 'icon' => 'flags-rs'],
                    ['label' => 'ru', 'value' => 'ru', 'icon' => 'flags-ru'],
                    ['label' => 'rw', 'value' => 'rw', 'icon' => 'flags-rw'],
                    ['label' => 'sa', 'value' => 'sa', 'icon' => 'flags-sa'],
                    ['label' => 'sb', 'value' => 'sb', 'icon' => 'flags-sb'],
                    ['label' => 'sc', 'value' => 'sc', 'icon' => 'flags-sc'],
                    ['label' => 'gb-sct', 'value' => 'gb-sct', 'icon' => 'flags-gb-sct'],
                    ['label' => 'sd', 'value' => 'sd', 'icon' => 'flags-sd'],
                    ['label' => 'se', 'value' => 'se', 'icon' => 'flags-se'],
                    ['label' => 'sg', 'value' => 'sg', 'icon' => 'flags-sg'],
                    ['label' => 'sh', 'value' => 'sh', 'icon' => 'flags-sh'],
                    ['label' => 'si', 'value' => 'si', 'icon' => 'flags-si'],
                    ['label' => 'sj', 'value' => 'sj', 'icon' => 'flags-sj'],
                    ['label' => 'sk', 'value' => 'sk', 'icon' => 'flags-sk'],
                    ['label' => 'sl', 'value' => 'sl', 'icon' => 'flags-sl'],
                    ['label' => 'sm', 'value' => 'sm', 'icon' => 'flags-sm'],
                    ['label' => 'sn', 'value' => 'sn', 'icon' => 'flags-sn'],
                    ['label' => 'so', 'value' => 'so', 'icon' => 'flags-so'],
                    ['label' => 'sr', 'value' => 'sr', 'icon' => 'flags-sr'],
                    ['label' => 'ss', 'value' => 'ss', 'icon' => 'flags-ss'],
                    ['label' => 'st', 'value' => 'st', 'icon' => 'flags-st'],
                    ['label' => 'sv', 'value' => 'sv', 'icon' => 'flags-sv'],
                    ['label' => 'sx', 'value' => 'sx', 'icon' => 'flags-sx'],
                    ['label' => 'sy', 'value' => 'sy', 'icon' => 'flags-sy'],
                    ['label' => 'sz', 'value' => 'sz', 'icon' => 'flags-sz'],
                    ['label' => 'tc', 'value' => 'tc', 'icon' => 'flags-tc'],
                    ['label' => 'td', 'value' => 'td', 'icon' => 'flags-td'],
                    ['label' => 'tf', 'value' => 'tf', 'icon' => 'flags-tf'],
                    ['label' => 'tg', 'value' => 'tg', 'icon' => 'flags-tg'],
                    ['label' => 'th', 'value' => 'th', 'icon' => 'flags-th'],
                    ['label' => 'tj', 'value' => 'tj', 'icon' => 'flags-tj'],
                    ['label' => 'tk', 'value' => 'tk', 'icon' => 'flags-tk'],
                    ['label' => 'tl', 'value' => 'tl', 'icon' => 'flags-tl'],
                    ['label' => 'tm', 'value' => 'tm', 'icon' => 'flags-tm'],
                    ['label' => 'tn', 'value' => 'tn', 'icon' => 'flags-tn'],
                    ['label' => 'to', 'value' => 'to', 'icon' => 'flags-to'],
                    ['label' => 'tr', 'value' => 'tr', 'icon' => 'flags-tr'],
                    ['label' => 'tt', 'value' => 'tt', 'icon' => 'flags-tt'],
                    ['label' => 'tv', 'value' => 'tv', 'icon' => 'flags-tv'],
                    ['label' => 'tw', 'value' => 'tw', 'icon' => 'flags-tw'],
                    ['label' => 'tz', 'value' => 'tz', 'icon' => 'flags-tz'],
                    ['label' => 'ua', 'value' => 'ua', 'icon' => 'flags-ua'],
                    ['label' => 'ug', 'value' => 'ug', 'icon' => 'flags-ug'],
                    ['label' => 'um', 'value' => 'um', 'icon' => 'flags-um'],
                    ['label' => 'us', 'value' => 'us', 'icon' => 'flags-us'],
                    ['label' => 'uy', 'value' => 'uy', 'icon' => 'flags-uy'],
                    ['label' => 'uz', 'value' => 'uz', 'icon' => 'flags-uz'],
                    ['label' => 'va', 'value' => 'va', 'icon' => 'flags-va'],
                    ['label' => 'vc', 'value' => 'vc', 'icon' => 'flags-vc'],
                    ['label' => 've', 'value' => 've', 'icon' => 'flags-ve'],
                    ['label' => 'vg', 'value' => 'vg', 'icon' => 'flags-vg'],
                    ['label' => 'vi', 'value' => 'vi', 'icon' => 'flags-vi'],
                    ['label' => 'vn', 'value' => 'vn', 'icon' => 'flags-vn'],
                    ['label' => 'vu', 'value' => 'vu', 'icon' => 'flags-vu'],
                    ['label' => 'gb-wls', 'value' => 'gb-wls', 'icon' => 'flags-gb-wls'],
                    ['label' => 'wf', 'value' => 'wf', 'icon' => 'flags-wf'],
                    ['label' => 'ws', 'value' => 'ws', 'icon' => 'flags-ws'],
                    ['label' => 'ye', 'value' => 'ye', 'icon' => 'flags-ye'],
                    ['label' => 'yt', 'value' => 'yt', 'icon' => 'flags-yt'],
                    ['label' => 'za', 'value' => 'za', 'icon' => 'flags-za'],
                    ['label' => 'zm', 'value' => 'zm', 'icon' => 'flags-zm'],
                    ['label' => 'zw', 'value' => 'zw', 'icon' => 'flags-zw']
                ],
                'maxitems' => 1
            ]
        ]
    ]
];
